services:
  db:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      TZ: ${TZ:-Asia/Tokyo}
      POSTGRES_DB: ${POSTGRES_DB:-dev}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - ${POSTGRES_PORT:-5432}:5432
  pgweb:
    image: sosedoff/pgweb
    container_name: "pgweb"
    ports:
      - "8080:8081"
    environment:
      PGWEB_DATABASE_URL: ${PGWEB_DATABASE_URL:-}
    depends_on:
      - db